### ISSUE TITLE
Server down ?

### ISSUE THREAD

**Issue by fwolf** [djudman/evernote-telegram-bot#15]
Send message to @evernoterobot has no response from several days ago, even /help command .

**Comment by djudman** [comment]
It should working now. There are were some works in Digital Ocean and so my VPS was rebooted :(
Thanks for using bot and reporting issues!

**Comment by fwolf** [comment]
Thanks!

**Comment by fwolf** [comment]
Stop working this morning, can u check again？ thx

Dmitry Dorofeev <notifications@github.com>于2016年12月2日周五 15:25写道：

**Comment by djudman** [comment]
I'm sorry, it's my fault, I forgot renew SSL certificate :(
Done. Bot is working

**Comment by fwolf** [comment]
fine now 😊 thanks

Dmitry Dorofeev <notifications@github.com>于2016年12月6日周二 16:28写道：
