### ISSUE TITLE
authorization failed

### ISSUE THREAD

**Issue by androgyneutrois** [djudman/evernote-telegram-bot#17]
start with signing in...
![default](https://cloud.githubusercontent.com/assets/8966057/26337244/f2eba004-3fa9-11e7-8a82-a458a15ee154.jpg)
but the bot respond "**We are sorry, but you declined authorization** 😢" every time.

**Comment by djudman** [comment]
@androgyneutrois can you try now, please? It should working

**Comment by androgyneutrois** [comment]
@djudman yeah, it really works. thx!
