### ISSUE TITLE
Human-readable filenames

### ISSUE THREAD

**Issue by agrigoriev** [djudman/evernote-telegram-bot#18]
Files are saved without extensions and with GUID-like filenames.

**Comment by djudman** [comment]
@agrigoriev fixed. From now files saves with original names

**Comment by agrigoriev** [comment]
While forwarding image file:
<img width="398" alt="screenshot" src="https://user-images.githubusercontent.com/232081/30150271-5b52d6be-93b3-11e7-81b1-5dabf01c77ae.png">
