### ISSUE TITLE
Error while forwarding images to bot

### ISSUE THREAD

**Issue by agrigoriev** [djudman/evernote-telegram-bot#19]
https://user-images.githubusercontent.com/232081/30150271-5b52d6be-93b3-11e7-81b1-5dabf01c77ae.png

**Comment by fwolf** [comment]
Now its 'Accepted' status only again, maybe server problem ? 

![2017-09-11-100909-580x474](https://user-images.githubusercontent.com/67877/30255901-531cb680-96d9-11e7-9b1d-af65a0aacccc.png)

**Comment by djudman** [comment]
@agrigoriev fixed. Thanks for report!
