### ISSUE TITLE
Bot is dead

### ISSUE THREAD

**Issue by voron434** [djudman/evernote-telegram-bot#21]
Trying to send any messages to @evernoterobot, no any reply. Same with @dev_evernoterobot

**Comment by djudman** [comment]
it works

**Comment by iruno** [comment]
Both bots are not responding now. Please fix?

**Comment by djudman** [comment]
@iruno you can check. It works now.

**Comment by djudman** [comment]
Fixed.

**Comment by iruno** [comment]
@djudman Great, it works now! Thank you!
