### ISSUE TITLE
How to get Evernote access keys?

### ISSUE THREAD

**Issue by nsuvorov83** [djudman/evernote-telegram-bot#22]
Please share whole process. As I see a request for sandbox access is needed first, then the app should be activated for prod by special form request on official Evernote site. Too complex. Is there another way?

**Comment by djudman** [comment]
@nsuvorov83  you can go to https://dev.evernote.com/doc/ and press the green button "GET AN API KEY", then you have to fill some fields, select API permissions for your app and press button "Request Key".
I think it's not so complex ;)
