### ISSUE TITLE
No any text in Evernote if TG message contains photo

### ISSUE THREAD

**Issue by eirenik0** [djudman/evernote-telegram-bot#25]
When I forward message with photo(s) contain text description the only photo is added to Evernote.

**Comment by AuroraDysis** [comment]
This issue is caused by evernote-sdk: https://github.com/evernote/evernote-sdk-python3/issues/27
To fix it, just change `requirements.txt`
```
evernote3==1.25.14
```

**Comment by djudman** [comment]
I updated evernote sdk, so this bug is fixed
