### ISSUE TITLE
reconneting failes

### ISSUE THREAD

**Issue by feensucher** [djudman/evernote-telegram-bot#27]
Good evening Sir, 

unfortunately I am not able to connect your bot to Evernote.

I log in correctly, everything is released in Evernote - but then it shows
"internal server error"
Although the bot shows that it works. But - when I try to send a message to the bot - or try to forward a message - it always says 
"Error. You have to sign in to Evernote first. Send /start and press the button"

Tried it very often - also reinstalled Evernote - but always the same problem

Do you have a solution?
Unfortunately I have no programming skills , 

Thank you very much, Wolfgang

Translated with www.DeepL.com/Translator (free version)
![image](https://user-images.githubusercontent.com/66973751/84704782-a3e78d00-af5a-11ea-80cb-61053400f3c7.png)

**Comment by djudman** [comment]
@feensucher there was a bug in evernote sdk, so I updated it. Now the bot works correctly
