### ISSUE TITLE
Bot stopped working

### ISSUE THREAD

**Issue by jagr21** [djudman/evernote-telegram-bot#31]
Bot stop saving notes and responding to commands a couple of days ago, any idea why? :(

**Comment by djudman** [comment]
@jagr21 please, check, it should be live from now. There was a problem with domain name (it was expired)

**Comment by jagr21** [comment]
> @jagr21 please, check, it should be live from now. There was a problem with domain name (it was expired)

Can confirm it's working again, thanks!

**Comment by pterodactylsupplies** [comment]
Still not working. "text accepted", but not saved.
