### ISSUE TITLE
Bot is not working

### ISSUE THREAD

**Issue by pterodactylsupplies** [djudman/evernote-telegram-bot#33]
"Text accepted", but not saved.

**Comment by djudman** [comment]
@pterodactylsupplies please check, it works now

**Comment by pterodactylsupplies** [comment]
No, it doesn't. "Text accepted", nothing happens after that. What can I do if the problem is on my side maybe?

**Comment by Opylat** [comment]
![image](https://user-images.githubusercontent.com/107822598/181916294-81511ddb-b953-47c2-96d3-f378a47b2aeb.png)
New problem!

**Comment by djudman** [comment]
@Opylat fixed

**Comment by DerevenetsArtyom** [comment]
@djudman hey! It looks like the bot stopped responding again :fearful:
